AllCops:
  TargetRubyVersion: 3.2.2

Style/StringLiterals:
  Enabled: true
  # EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  # EnforcedStyle: double_quotes

Style/ExplicitBlockArgument:
  Enable: false

Layout/LineLength:
  Max: 120
